import { test } from 'node:test';
import assert from 'node:assert/strict';
import { loadContent } from '../content/index.ts';
import { createInitialState, createInitialTree, dispatch, fromJSON, toJSON,
  createChallengeStudioDraft, runCommand, type HistoryTree } from './index.ts';

const content = loadContent();
test('fresh Mở đầu/C1 → C2 through commands, partial draft reload, papers, loan, ending and +100 exactly', () => {
  let tree: HistoryTree = createInitialTree(createInitialState(content));
  const state = () => tree.nodes[tree.headId].snapshot;
  const send = (type: string, payload: unknown) => {
    const result = dispatch(tree,{type,payload},content); assert.ok(result.ok,!result.ok?result.reason:'');
    if (result.ok) tree=result.tree;
  };
  const tap = (id: string) => {
    const progress = state().journey[state().currentChapter];
    const hotspot = content.chapters[state().currentChapter].areas.find(a=>a.id===progress.currentArea)!.interactables.find(i=>i.id===id)!;
    send('interact',{targetId:id,playerPos:hotspot.pos});
  };
  const read = () => {let budget=50;while(state().journey[state().currentChapter].activeDialogue){assert.ok(budget-->0);send('dialogue/advance',{});}};
  const solve = (puzzleId: string, answer: unknown) => send('puzzle/submit',{puzzleId,answer});
  const go = (areaId: string) => send('area/goTo',{areaId});
  const reload = () => {const restored=fromJSON(toJSON(tree),content);assert.ok(restored.ok);if(restored.ok)tree=restored.tree;};
  tap('hitbox-stairs');read();go('c0-s2-gac-xep-chiec-ruong');solve('p-c0-cloth','interact');tap('hitbox-sewing-basket');
  solve('p-c0-mannequin-hand','kim_gut_bang_bac');solve('p-c0-chest-unlock','chia_khoa_dong_ba_chau');read();
  send('chapter/complete',{chapterId:'prologue'});send('reward/claim',{chapterId:'prologue'});send('chapter/enter',{chapterId:'c1'});
  tap('hitbox-loom-shuttle');tap('hitbox-belt-rack');send('item/combine',{itemIds:['con_thoi_go_mun','that_lung_lua_cham']});
  send('item/use',{itemId:'dung_cu_moc_then_cua',targetPuzzleId:'p-c1-escape'});go('c1-s2-ban-tho-nha-tho-ho');
  solve('p-c1-altar-cut-threads','keo_may_bang_dong');read();go('c1-s3-cong-dinh-doi-dau');
  solve('p-c1-present-contract','to_van_tu_cam_co_dat');solve('p-c1-present-letter','buc_thu_tay_chong_cu_Cam');tap('hitbox-stone-step');read();
  solve('p-c1-styling-cam',{silhouette:'ngu_than_tay_chen',garmentId:'ao-ngu-than-tay-chen',headwearId:'khan-van-den',footwearId:'guoc-moc'});
  tap('hitbox-village-gate-exit');read();send('chapter/complete',{chapterId:'c1'});send('reward/claim',{chapterId:'c1'});
  assert.equal(state().wallet.senNgoc,250);
  send('chapter/enter',{chapterId:'c2'});
  assert.equal(state().journey.c2.activeDialogue?.dialogueId,'d-c2-ca-nghi');
  reload();read();
  tap('hitbox-drawing-desk');tap('hitbox-fabric-basket');tap('hitbox-gas-lamp');tap('hitbox-french-window');
  const pieces=['manh_ban_ve_ao_dai_1','manh_ban_ve_ao_dai_2','manh_ban_ve_ao_dai_3','manh_ban_ve_ao_dai_4'];
  send('puzzle/open',{puzzleId:'p-c2-sketch-assemble'});
  send('puzzle/updateDraft',{puzzleId:'p-c2-sketch-assemble',draft:{type:'order',answer:[pieces[2],pieces[0]]}});
  send('puzzle/close',{});reload();send('puzzle/open',{puzzleId:'p-c2-sketch-assemble'});
  const session=state().activeSession;
  assert.deepEqual(session?.type==='puzzle'&&session.data.answer,[pieces[2],pieces[0]]);
  solve('p-c2-sketch-assemble',[...pieces].reverse());
  assert.equal(state().journey.c2.solvedPuzzleIds.includes('p-c2-sketch-assemble'),false);
  solve('p-c2-sketch-assemble',pieces);read();go('c2-s2-kho-vai-hang-dao');
  tap('hitbox-grandfather-clock');solve('p-c2-safe-open','chia_khoa_ket_sat_bang_thau');reload();
  assert.equal(state().journey.c2.activeDialogue?.dialogueId,'d-c2-bien-lai');send('dialogue/advance',{});reload();
  assert.equal(state().journey.c2.activeDialogue?.dialogueId,'d-c2-giao-keo');send('dialogue/advance',{});
  go('c2-s3-phong-trien-lam-doi-dau');
  solve('p-c2-present-receipt','bien_lai_tra_no_goc_1935');solve('p-c2-present-sketch','ban_ve_ao_dai_tan_thoi');
  const before=structuredClone(state());
  assert.equal(before.closet.unlockedGarmentIds.includes('ao-dai-lemur'),false);
  const draft=createChallengeStudioDraft(state(),'p-c2-styling-loan',content);assert.ok(draft.ok);
  assert.deepEqual(state(),before);
  const answer={silhouette:'tan_thoi',garmentId:'ao-dai-lemur',headwearId:'khan-van-den',footwearId:'guoc-moc',color0:'#123456'};
  send('puzzle/updateDraft',{puzzleId:'p-c2-styling-loan',draft:{type:'styling',answer}});reload();
  solve('p-c2-styling-loan',answer);
  assert.equal(runCommand(state(),{type:'chapter/complete',payload:{chapterId:'c2'}},content).ok,false);
  send('dialogue/advance',{});reload();
  assert.equal(state().journey.c2.activeDialogue?.currentNodeId,'node-2');
  assert.equal(runCommand(state(),{type:'reward/claim',payload:{chapterId:'c2'}},content).ok,false);
  send('dialogue/advance',{});send('chapter/complete',{chapterId:'c2'});reload();
  send('reward/claim',{chapterId:'c2'});reload();
  assert.equal(state().wallet.senNgoc,350);
  assert.deepEqual(state().journey.c2.solvedPuzzleIds,content.chapters.c2.puzzles.map(p=>p.id));
  assert.ok(content.chapters.c2.chapter.reward.garmentIds!.every(id=>state().closet.unlockedGarmentIds.includes(id)));
  assert.ok(content.chapters.c2.chapter.reward.cardIds!.every(id=>state().museum.unlockedCardIds?.includes(id)));
  assert.deepEqual(state().museum.readCardIds,[]);
  assert.equal(runCommand(state(),{type:'reward/claim',payload:{chapterId:'c2'}},content).ok,false);
});
