import type { Request, Response } from 'express';
import { z } from 'zod';
import { Type } from '@google/genai';
import { ai } from './gemini-client.ts';
import { aiCache } from './cache.ts';
import { AI_MODELS } from '../../config/ai-models.ts';
import { sanitizeUserText, toFallbackReason, UNTRUSTED_DATA_NOTICE, type FallbackReason } from './sanitize.ts';
import studioJson from '../../content/studio.json';
import { CultureCardIdSchema } from '../../content/schema.ts';

// ----------------------------------------------------
// 1. Content IDs and Lookups from studio.json
// ----------------------------------------------------

const VALID_GARMENTS = new Map(studioJson.garments.map((g) => [g.id, g]));
const VALID_ACCESSORIES = new Map(studioJson.accessories.map((a) => [a.id, a]));

export const GarmentEnum = z.enum([
  'ao-tu-than',
  'ao-ngu-than-tay-chen',
  'ao-ngu-than-tay-thung',
  'ao-dai-lemur',
  'ao-dai-tan-thoi-vang-mo-ga',
  'ao-dai-raglan',
  'ao-dai-co-thuyen',
  'ao-dai-cuoi-phin',
  'ao-dai-popolin',
  'ao-ngu-than-remix-2026'
]);

export const AccessoryEnum = z.enum([
  'khan-van-den',
  'khan-van-hoang-yen',
  'khan-mo-qua',
  'non-quai-thao',
  'non-la',
  'guoc-moc',
  'hai-theu',
  'kieng-bac',
  'kinh-mat-meo',
  'quat-lua'
]);

// Verified comment templates stored in content, never freely generated by AI
export const STYLIST_COMMENT_TEMPLATES: Record<string, string> = {
  tet_truyen_thong: 'Mèo Nếp gợi ý bộ lễ phục {garmentName} kết hợp cùng {accessories}, mang sắc xuân rạng rỡ và phúc lộc đầu năm.',
  tet_du_xuan: 'Bộ áo {garmentName} thanh nhã phối cùng {accessories}, rất duyên dáng khi du xuân và mừng tuổi ông bà.',
  dam_cuoi_trang_trong: 'Bộ lễ phục {garmentName} uy nghiêm kết hợp {accessories}, giữ trọn nét tôn nghiêm ngày vu quy đại lễ.',
  dam_cuoi_thanh_lich: 'Cách phối {garmentName} cùng {accessories} nền nã, vừa trang trọng vừa tôn nét dịu dàng người dự tiệc cưới.',
  be_giang_hoc_duong: 'Tà áo {garmentName} trắng thanh khôi điểm xuyết {accessories}, gắn liền với kỷ niệm trang lưu bút tuổi học trò.',
  be_giang_tuoi_tre: 'Bộ {garmentName} phối cùng {accessories} nhẹ nhàng, giúp bạn tự tin ghi lại khoảnh khắc bế giảng rạng rỡ.',
  le_chua_thanh_tinh: 'Trang phục {garmentName} mộc mạc kín đáo cùng {accessories}, giữ lòng thanh tịnh nơi cửa Phật linh thiêng.',
  le_chua_kin_dao: 'Bộ y phục {garmentName} gam màu trầm trang nhã cùng {accessories}, thể hiện lòng thành kính khi dâng hương lễ Phật.',
  vieng_tang_trang_nghiem: 'Bộ {garmentName} tiết chế màu sắc theo đúng lễ nghi, thành kính phân ưu cùng gia quyến.',
  dao_pho_cuoi_tuan: 'Áo {garmentName} phối cùng {accessories} phóng khoáng và bay bổng cho buổi dạo phố cuối tuần râm mát.',
  dao_pho_hien_dai: 'Nét giao thoa giữa {garmentName} và {accessories}, mang lại phong cách Việt phục Remix đầy tự tin.',
  mac_dinh_nep: 'Nếp đã chọn sẵn 3 bộ truyền thống chuẩn mực nhất cho dịp này rồi đây mướp!'
};

const TemplateIdEnum = z.enum([
  'tet_truyen_thong',
  'tet_du_xuan',
  'dam_cuoi_trang_trong',
  'dam_cuoi_thanh_lich',
  'be_giang_hoc_duong',
  'be_giang_tuoi_tre',
  'le_chua_thanh_tinh',
  'le_chua_kin_dao',
  'vieng_tang_trang_nghiem',
  'dao_pho_cuoi_tuan',
  'dao_pho_hien_dai',
  'mac_dinh_nep'
]);

// ----------------------------------------------------
// 2. Output Data Schemas
// ----------------------------------------------------

export const StylistRawSuggestionSchema = z.object({
  garmentId: GarmentEnum.catch('ao-ngu-than-tay-chen'),
  accessoryIds: z.array(AccessoryEnum).catch(['khan-van-den', 'guoc-moc']),
  cultureCardId: CultureCardIdSchema.catch('card-ngu-than-nguyen-dynasty'),
  templateId: TemplateIdEnum.catch('mac_dinh_nep')
});

export interface StylistOutfitSuggestion {
  garmentId: string;
  garmentName: string;
  silhouette: string;
  colorPalette: [string, string, string, string];
  accessoryIds: string[];
  accessoryNames: string[];
  cultureCardId: string;
  templateId: string;
  catComment: string;
}

// ----------------------------------------------------
// 3. Static Fallback Suggestions (By Event)
// ----------------------------------------------------

export const STATIC_FALLBACK_SUGGESTIONS: Record<string, StylistOutfitSuggestion[]> = {
  tet: [
    {
      garmentId: 'ao-ngu-than-tay-chen',
      garmentName: 'Áo ngũ thân tay chẽn',
      silhouette: 'ngu_than_tay_chen',
      colorPalette: ['#E6A1B0', '#C25975', '#802D45', '#3A0D1B'],
      accessoryIds: ['khan-van-hoang-yen', 'guoc-moc'],
      accessoryNames: ['Khăn vấn hoàng yến', 'Guốc mộc quai nhung'],
      cultureCardId: 'ao-ngu-than-tay-chen',
      templateId: 'tet_truyen_thong',
      catComment: 'Mèo Nếp gợi ý bộ lễ phục Áo ngũ thân tay chẽn kết hợp cùng Khăn vấn hoàng yến, Guốc mộc quai nhung, mang sắc xuân rạng rỡ và phúc lộc đầu năm.'
    },
    {
      garmentId: 'ao-ngu-than-remix-2026',
      garmentName: 'Áo ngũ thân Remix 2026',
      silhouette: 'ngu_than_tay_chen',
      colorPalette: ['#FFD166', '#EF476F', '#06D6A0', '#118AB2'],
      accessoryIds: ['quat-lua', 'guoc-moc'],
      accessoryNames: ['Quạt lụa thêu hoa', 'Guốc mộc quai nhung'],
      cultureCardId: 'card-viet-phuc-remix-tuong-lai',
      templateId: 'tet_du_xuan',
      catComment: 'Bộ áo Áo ngũ thân Remix 2026 thanh nhã phối cùng Quạt lụa thêu hoa, Guốc mộc quai nhung, rất duyên dáng khi du xuân và mừng tuổi ông bà.'
    },
    {
      garmentId: 'ao-tu-than',
      garmentName: 'Áo tứ thân',
      silhouette: 'tu_than',
      colorPalette: ['#C4A482', '#8B5A2B', '#5C3A21', '#2C1608'],
      accessoryIds: ['khan-mo-qua', 'non-quai-thao'],
      accessoryNames: ['Khăn mỏ quạ', 'Nón ba tầm quai thao'],
      cultureCardId: 'ao-tu-than',
      templateId: 'tet_truyen_thong',
      catComment: 'Mèo Nếp gợi ý bộ lễ phục Áo tứ thân kết hợp cùng Khăn mỏ quạ, Nón ba tầm quai thao, mang sắc xuân rạng rỡ và phúc lộc đầu năm.'
    }
  ],
  dam_cuoi: [
    {
      garmentId: 'ao-ngu-than-tay-thung',
      garmentName: 'Áo tấc tay thụng',
      silhouette: 'ngu_than_tay_thung',
      colorPalette: ['#E8C547', '#C49B18', '#7D620A', '#382B02'],
      accessoryIds: ['khan-van-hoang-yen', 'hai-theu'],
      accessoryNames: ['Khăn vấn hoàng yến', 'Hài thêu hoa sen'],
      cultureCardId: 'trang-phuc-hon-le-truyen-thong',
      templateId: 'dam_cuoi_trang_trong',
      catComment: 'Bộ lễ phục Áo tấc tay thụng uy nghiêm kết hợp Khăn vấn hoàng yến, Hài thêu hoa sen, giữ trọn nét tôn nghiêm ngày vu quy đại lễ.'
    },
    {
      garmentId: 'ao-dai-cuoi-phin',
      garmentName: 'Áo dài cưới vải phin 1982',
      silhouette: 'tan_thoi',
      colorPalette: ['#FFFFFF', '#F0EFEB', '#D6CCC2', '#8D8175'],
      accessoryIds: ['kieng-bac', 'hai-theu'],
      accessoryNames: ['Kiềng bạc chạm hoa', 'Hài thêu hoa sen'],
      cultureCardId: 'card-ao-dai-thoi-bao-cap-1980',
      templateId: 'dam_cuoi_thanh_lich',
      catComment: 'Cách phối Áo dài cưới vải phin 1982 cùng Kiềng bạc chạm hoa, Hài thêu hoa sen nền nã, vừa trang trọng vừa tôn nét dịu dàng người dự tiệc cưới.'
    },
    {
      garmentId: 'ao-dai-co-thuyen',
      garmentName: 'Áo dài cổ thuyền',
      silhouette: 'tan_thoi',
      colorPalette: ['#90E0EF', '#00B4D8', '#0077B6', '#03045E'],
      accessoryIds: ['kieng-bac', 'quat-lua'],
      accessoryNames: ['Kiềng bạc chạm hoa', 'Quạt lụa thêu hoa'],
      cultureCardId: 'card-ky-thuat-ao-dai-raglan-1960',
      templateId: 'dam_cuoi_thanh_lich',
      catComment: 'Cách phối Áo dài cổ thuyền cùng Kiềng bạc chạm hoa, Quạt lụa thêu hoa nền nã, vừa trang trọng vừa tôn nét dịu dàng người dự tiệc cưới.'
    }
  ],
  be_giang: [
    {
      garmentId: 'ao-dai-tan-thoi-vang-mo-ga',
      garmentName: 'Áo dài tân thời cổ đứng',
      silhouette: 'tan_thoi',
      colorPalette: ['#FFF3B0', '#E9D8A6', '#9B8342', '#3D3315'],
      accessoryIds: ['non-la', 'guoc-moc'],
      accessoryNames: ['Nón lá chóp nhọn', 'Guốc mộc quai nhung'],
      cultureCardId: 'ao-dai-tan-thoi-lemur',
      templateId: 'be_giang_hoc_duong',
      catComment: 'Tà áo Áo dài tân thời cổ đứng trắng thanh khôi điểm xuyết Nón lá chóp nhọn, Guốc mộc quai nhung, gắn liền với kỷ niệm trang lưu bút tuổi học trò.'
    },
    {
      garmentId: 'ao-dai-popolin',
      garmentName: 'Áo dài popolin hoa cúc',
      silhouette: 'tan_thoi',
      colorPalette: ['#E9EDC9', '#CCD5AE', '#D4A373', '#606C38'],
      accessoryIds: ['guoc-moc'],
      accessoryNames: ['Guốc mộc quai nhung'],
      cultureCardId: 'card-ao-dai-thoi-bao-cap-1980',
      templateId: 'be_giang_tuoi_tre',
      catComment: 'Bộ Áo dài popolin hoa cúc phối cùng Guốc mộc quai nhung nhẹ nhàng, giúp bạn tự tin ghi lại khoảnh khắc bế giảng rạng rỡ.'
    },
    {
      garmentId: 'ao-dai-raglan',
      garmentName: 'Áo dài tay raglan 1960',
      silhouette: 'tan_thoi',
      colorPalette: ['#A8DADC', '#457B9D', '#1D3557', '#0D1B2A'],
      accessoryIds: ['non-la', 'guoc-moc'],
      accessoryNames: ['Nón lá chóp nhọn', 'Guốc mộc quai nhung'],
      cultureCardId: 'card-ky-thuat-ao-dai-raglan-1960',
      templateId: 'be_giang_hoc_duong',
      catComment: 'Tà áo Áo dài tay raglan 1960 trắng thanh khôi điểm xuyết Nón lá chóp nhọn, Guốc mộc quai nhung, gắn liền với kỷ niệm trang lưu bút tuổi học trò.'
    }
  ],
  le_chua: [
    {
      garmentId: 'ao-tu-than',
      garmentName: 'Áo tứ thân',
      silhouette: 'tu_than',
      colorPalette: ['#C4A482', '#8B5A2B', '#5C3A21', '#2C1608'],
      accessoryIds: ['khan-mo-qua', 'guoc-moc'],
      accessoryNames: ['Khăn mỏ quạ', 'Guốc mộc quai nhung'],
      cultureCardId: 'ao-tu-than',
      templateId: 'le_chua_thanh_tinh',
      catComment: 'Trang phục Áo tứ thân mộc mạc kín đáo cùng Khăn mỏ quạ, Guốc mộc quai nhung, giữ lòng thanh tịnh nơi cửa Phật linh thiêng.'
    },
    {
      garmentId: 'ao-ngu-than-tay-chen',
      garmentName: 'Áo ngũ thân tay chẽn',
      silhouette: 'ngu_than_tay_chen',
      colorPalette: ['#E6A1B0', '#C25975', '#802D45', '#3A0D1B'],
      accessoryIds: ['khan-van-den', 'guoc-moc'],
      accessoryNames: ['Khăn vấn nhung đen', 'Guốc mộc quai nhung'],
      cultureCardId: 'card-ngu-than-nguyen-dynasty',
      templateId: 'le_chua_kin_dao',
      catComment: 'Bộ y phục Áo ngũ thân tay chẽn gam màu trầm trang nhã cùng Khăn vấn nhung đen, Guốc mộc quai nhung, thể hiện lòng thành kính khi dâng hương lễ Phật.'
    },
    {
      garmentId: 'ao-ngu-than-tay-thung',
      garmentName: 'Áo tấc tay thụng',
      silhouette: 'ngu_than_tay_thung',
      colorPalette: ['#E8C547', '#C49B18', '#7D620A', '#382B02'],
      accessoryIds: ['khan-van-den', 'guoc-moc'],
      accessoryNames: ['Khăn vấn nhung đen', 'Guốc mộc quai nhung'],
      cultureCardId: 'ao-ngu-than-tay-thung',
      templateId: 'le_chua_kin_dao',
      catComment: 'Bộ y phục Áo tấc tay thụng gam màu trầm trang nhã cùng Khăn vấn nhung đen, Guốc mộc quai nhung, thể hiện lòng thành kính khi dâng hương lễ Phật.'
    }
  ],
  vieng_tang: [
    {
      garmentId: 'ao-ngu-than-tay-chen',
      garmentName: 'Áo ngũ thân tay chẽn',
      silhouette: 'ngu_than_tay_chen',
      colorPalette: ['#E6A1B0', '#C25975', '#802D45', '#3A0D1B'],
      accessoryIds: ['khan-van-den', 'guoc-moc'],
      accessoryNames: ['Khăn vấn nhung đen', 'Guốc mộc quai nhung'],
      cultureCardId: 'trang-phuc-tang-le-truyen-thong',
      templateId: 'vieng_tang_trang_nghiem',
      catComment: 'Bộ Áo ngũ thân tay chẽn tiết chế màu sắc theo đúng lễ nghi, thành kính phân ưu cùng gia quyến.'
    },
    {
      garmentId: 'ao-ngu-than-tay-thung',
      garmentName: 'Áo tấc tay thụng',
      silhouette: 'ngu_than_tay_thung',
      colorPalette: ['#E8C547', '#C49B18', '#7D620A', '#382B02'],
      accessoryIds: ['khan-van-den', 'guoc-moc'],
      accessoryNames: ['Khăn vấn nhung đen', 'Guốc mộc quai nhung'],
      cultureCardId: 'trang-phuc-tang-le-truyen-thong',
      templateId: 'vieng_tang_trang_nghiem',
      catComment: 'Bộ Áo tấc tay thụng tiết chế màu sắc theo đúng lễ nghi, thành kính phân ưu cùng gia quyến.'
    },
    {
      garmentId: 'ao-tu-than',
      garmentName: 'Áo tứ thân',
      silhouette: 'tu_than',
      colorPalette: ['#C4A482', '#8B5A2B', '#5C3A21', '#2C1608'],
      accessoryIds: ['khan-mo-qua', 'guoc-moc'],
      accessoryNames: ['Khăn mỏ quạ', 'Guốc mộc quai nhung'],
      cultureCardId: 'trang-phuc-tang-le-truyen-thong',
      templateId: 'vieng_tang_trang_nghiem',
      catComment: 'Bộ Áo tứ thân tiết chế màu sắc theo đúng lễ nghi, thành kính phân ưu cùng gia quyến.'
    }
  ],
  dao_pho: [
    {
      garmentId: 'ao-dai-raglan',
      garmentName: 'Áo dài tay raglan 1960',
      silhouette: 'tan_thoi',
      colorPalette: ['#A8DADC', '#457B9D', '#1D3557', '#0D1B2A'],
      accessoryIds: ['kinh-mat-meo', 'guoc-moc'],
      accessoryNames: ['Kính mắt mèo thời thượng', 'Guốc mộc quai nhung'],
      cultureCardId: 'card-ky-thuat-ao-dai-raglan-1960',
      templateId: 'dao_pho_cuoi_tuan',
      catComment: 'Áo Áo dài tay raglan 1960 phối cùng Kính mắt mèo thời thượng, Guốc mộc quai nhung phóng khoáng và bay bổng cho buổi dạo phố cuối tuần râm mát.'
    },
    {
      garmentId: 'ao-dai-lemur',
      garmentName: 'Áo dài Lemur 1934',
      silhouette: 'tan_thoi',
      colorPalette: ['#FFCCD5', '#FB6F92', '#C9365F', '#5E0E27'],
      accessoryIds: ['quat-lua', 'guoc-moc'],
      accessoryNames: ['Quạt lụa thêu hoa', 'Guốc mộc quai nhung'],
      cultureCardId: 'card-phong-trao-ao-dai-lemur-1934',
      templateId: 'dao_pho_cuoi_tuan',
      catComment: 'Áo Áo dài Lemur 1934 phối cùng Quạt lụa thêu hoa, Guốc mộc quai nhung phóng khoáng và bay bổng cho buổi dạo phố cuối tuần râm mát.'
    },
    {
      garmentId: 'ao-ngu-than-remix-2026',
      garmentName: 'Áo ngũ thân Remix 2026',
      silhouette: 'ngu_than_tay_chen',
      colorPalette: ['#FFD166', '#EF476F', '#06D6A0', '#118AB2'],
      accessoryIds: ['quat-lua', 'kieng-bac'],
      accessoryNames: ['Quạt lụa thêu hoa', 'Kiềng bạc chạm hoa'],
      cultureCardId: 'card-viet-phuc-remix-tuong-lai',
      templateId: 'dao_pho_hien_dai',
      catComment: 'Nét giao thoa giữa Áo ngũ thân Remix 2026 và Quạt lụa thêu hoa, Kiềng bạc chạm hoa, mang lại phong cách Việt phục Remix đầy tự tin.'
    }
  ]
};

// ----------------------------------------------------
// 4. Request Handler: POST /api/ai/stylist
// ----------------------------------------------------
export async function handleStylist(req: Request, res: Response) {
  const { eventId, weather: rawWeather } = req.body || {};
  const weather = sanitizeUserText(rawWeather, 80) || 'Nắng ấm nhẹ nhàng';
  const normalizedEventId =
    typeof eventId === 'string' && Object.hasOwn(STATIC_FALLBACK_SUGGESTIONS, eventId) ? eventId : 'dao_pho';
  const fallback = STATIC_FALLBACK_SUGGESTIONS[normalizedEventId] || STATIC_FALLBACK_SUGGESTIONS.dao_pho;

  try {
    // Check cache
    const cacheKey = `stylist_${aiCache.hashKey({ eventId: normalizedEventId, weather })}`;
    const cached = aiCache.get<StylistOutfitSuggestion[]>(cacheKey);
    if (cached) {
      return res.json({
        ok: true,
        data: { suggestions: cached },
        cached: true
      });
    }

    // Call Gemini with strict structured output schema
    const systemInstruction = [
      `Bạn là chú mèo Stylist Nếp thông thái trong Tiệm May Nếp.`,
      `Người dùng đang chuẩn bị trang phục cho một sự kiện với một điều kiện thời tiết, cung cấp trong khối DATA (JSON) của tin nhắn người dùng.`,
      UNTRUSTED_DATA_NOTICE,
      `Hãy đề xuất đúng 3 gợi ý phối đồ.`,
      `Mỗi gợi ý CHỈ được chọn các ID hợp lệ sau:`,
      `- garmentId: một trong [ao-tu-than, ao-ngu-than-tay-chen, ao-ngu-than-tay-thung, ao-dai-lemur, ao-dai-tan-thoi-vang-mo-ga, ao-dai-raglan, ao-dai-co-thuyen, ao-dai-cuoi-phin, ao-dai-popolin, ao-ngu-than-remix-2026]`,
      `- accessoryIds: danh sách từ [khan-van-den, khan-van-hoang-yen, khan-mo-qua, non-quai-thao, non-la, guoc-moc, hai-theu, kieng-bac, kinh-mat-meo, quat-lua]`,
      `- cultureCardId: một ID thẻ văn hóa phù hợp`,
      `- templateId: một trong các mã template [tet_truyen_thong, tet_du_xuan, dam_cuoi_trang_trong, dam_cuoi_thanh_lich, be_giang_hoc_duong, be_giang_tuoi_tre, le_chua_thanh_tinh, le_chua_kin_dao, vieng_tang_trang_nghiem, dao_pho_cuoi_tuan, dao_pho_hien_dai, mac_dinh_nep]`,
      `TUYỆT ĐỐI KHÔNG tự bịa text nhận xét tự do.`
    ].join('\n');
    const prompt = `DATA: ${JSON.stringify({ eventId: normalizedEventId, weather })}`;

    const response = await ai.models.generateContent({
      model: AI_MODELS.VISION_MODEL,
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            suggestions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  garmentId: { type: Type.STRING },
                  accessoryIds: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING }
                  },
                  cultureCardId: { type: Type.STRING },
                  templateId: { type: Type.STRING }
                },
                required: ['garmentId', 'accessoryIds', 'cultureCardId', 'templateId']
              }
            }
          },
          required: ['suggestions']
        }
      }
    });

    const rawText = response.text?.trim() || '{}';
    let parsed: any;
    try {
      parsed = JSON.parse(rawText);
    } catch {
      parsed = { suggestions: [] };
    }

    const rawSuggestions = Array.isArray(parsed?.suggestions) ? parsed.suggestions : [];
    if (rawSuggestions.length === 0) {
      return res.json({
        ok: false,
        fallback: { suggestions: fallback, reason: 'invalid_output' satisfies FallbackReason }
      });
    }

    // Build hydrated suggestions strictly matching content
    const validatedSuggestions: StylistOutfitSuggestion[] = [];

    for (let i = 0; i < Math.min(3, rawSuggestions.length); i++) {
      const raw = StylistRawSuggestionSchema.parse(rawSuggestions[i]);
      const garment = VALID_GARMENTS.get(raw.garmentId) || VALID_GARMENTS.get('ao-ngu-than-tay-chen')!;
      
      const accNames: string[] = [];
      const validAccIds: string[] = [];
      for (const accId of raw.accessoryIds) {
        const acc = VALID_ACCESSORIES.get(accId);
        if (acc) {
          validAccIds.push(acc.id);
          accNames.push(acc.name);
        }
      }

      // Compute template-based cat comment
      const templateStr = STYLIST_COMMENT_TEMPLATES[raw.templateId] || STYLIST_COMMENT_TEMPLATES.mac_dinh_nep;
      const accessoriesSummary = accNames.length > 0 ? accNames.join(', ') : 'phụ kiện thanh lịch';
      const catComment = templateStr
        .replace('{garmentName}', garment.name)
        .replace('{accessories}', accessoriesSummary);

      validatedSuggestions.push({
        garmentId: garment.id,
        garmentName: garment.name,
        silhouette: garment.silhouette,
        colorPalette: [
          garment.defaultColorPalette[0] || '#FFFFFF',
          garment.defaultColorPalette[1] || '#CCCCCC',
          garment.defaultColorPalette[2] || '#999999',
          garment.defaultColorPalette[3] || '#333333'
        ] as [string, string, string, string],
        accessoryIds: validAccIds,
        accessoryNames: accNames,
        cultureCardId: raw.cultureCardId,
        templateId: raw.templateId,
        catComment
      });
    }

    // If less than 3, pad with fallback items
    while (validatedSuggestions.length < 3) {
      const padItem = fallback[validatedSuggestions.length] || fallback[0];
      validatedSuggestions.push(padItem);
    }

    aiCache.set(cacheKey, validatedSuggestions);

    return res.json({
      ok: true,
      data: { suggestions: validatedSuggestions }
    });
  } catch (err) {
    console.error('[AI] stylist failed:', err);
    return res.json({
      ok: false,
      fallback: {
        suggestions: fallback,
        reason: toFallbackReason(err),
        message: 'Chú mèo Stylist đang bận, tiệm gửi bạn vài gợi ý có sẵn nhé!'
      }
    });
  }
}
